// lib/vue/input.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue'
import { computed, onMounted, onUnmounted, ref } from 'vue'

import { REGEXP_ONLY_DIGITS } from '@lib/core'
import { onMount } from '@lib/core/internal/input'
import type { HTMLInputElementWithMetadata } from '@lib/core/internal/types'

import type { VueOTPInputProps } from './types'

defineOptions({
  name: 'OTPInput',
  inheritAttrs: false,
})

const {
  // Props
  maxlength,
  pattern = REGEXP_ONLY_DIGITS,
  inputmode = 'numeric',

  containerClass,

  // HTML defaults
  autocomplete = 'one-time-code',

  ...props
} = withDefaults(defineProps<VueOTPInputProps>(), {
  pattern: REGEXP_ONLY_DIGITS,
  inputmode: 'numeric',
})

const emit = defineEmits<{
  (event: 'complete', value: string): void
}>()

const value = defineModel({ default: '' })

/** Workarounds */
const onChange = (newValue: string) => {
  value.value = newValue
}
const regexp = computed(() =>
  pattern
    ? typeof pattern === 'string'
      ? new RegExp(pattern)
      : pattern
    : undefined,
)

/** Refs */
const containerRef = ref<HTMLDivElement | null>(null)
const inputRef = ref<HTMLInputElementWithMetadata | null>(null)
defineExpose({ ref: inputRef })

/** Mirror State for children-rendering-only purpose */
const mirrorHovering = ref(false)
const mirrorFocused = ref(false)
const mirrorSel = ref<[number, number]>([-1, -1])

let mounted: ReturnType<typeof onMount>
onMounted(() => {
  const container = containerRef.value
  const input = inputRef.value
  if (!container || !input) {
    return
  }

  mounted = onMount({
    container,
    input: input,
    metadata: {
      maxLength: maxlength,
      onChange,
      onComplete: t => emit('complete', t),
      regexp: regexp.value,
      updateMirror: (k, v) => {
        if (k === 'data-sel' && v !== undefined) {
          const [s, e] = v.split(',').map(Number)
          mirrorSel.value = [s, e]
        }
        if (k === 'data-is-focused') {
          mirrorFocused.value = Boolean(v)
        }
        if (k === 'data-is-hovering') {
          mirrorHovering.value = Boolean(v)
        }
      },
    },
  })
})
onUnmounted(() => {
  mounted !== undefined && mounted.unmount()
})

const slots = computed(() => {
  return Array.from({ length: maxlength }).map((_, slotIdx) => {
    const isActive =
      mirrorFocused.value &&
      mirrorSel.value[0] !== null &&
      mirrorSel.value[1] !== null &&
      ((mirrorSel.value[0] === mirrorSel.value[1] &&
        slotIdx === mirrorSel.value[0]) ||
        (slotIdx >= mirrorSel.value[0] && slotIdx < mirrorSel.value[1]))

    const char =
      value.value[slotIdx] !== undefined ? value.value[slotIdx] : null

    return {
      char,
      isActive,
      hasFakeCaret: isActive && char === null,
    }
  })
})

const inputStyle = {
  position: 'absolute',
  inset: 0,
  width: '100%',
  height: '100%',
  display: 'flex',
  textAlign: 'start',
  opacity: '1', // Mandatory for iOS hold-paste
  color: 'transparent',
  pointerEvents: 'all',
  background: 'transparent',
  caretColor: 'transparent',
  border: '0 solid transparent',
  outline: '0 solid transparent',
  lineHeight: '1',
  letterSpacing: '-.5em',
  fontSize: 'var(--root-height)',
} satisfies CSSProperties
</script>

<template>
  <div
    data-input-otp-container
    ref="containerRef"
    :style="{
      position: 'relative',
      userSelect: 'none',
      cursor: disabled ? 'default' : 'text',
    }"
    :class="containerClass"
  >
    <slot
      :slots="slots"
      :is-focused="mirrorFocused"
      :is-hovering="!disabled && mirrorHovering"
    />

    <input
      v-bind="{ ...$attrs, ...props }"
      :autocomplete="autocomplete"
      data-input-otp
      ref="inputRef"
      :style="inputStyle"
      :pattern="pattern"
      :inputmode="inputmode"
      :maxlength="maxlength"
      :value="value"
    />
  </div>
</template>

// lib/svelte/input.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy, onMount } from 'svelte'
  import type { HTMLInputAttributes } from 'svelte/elements'

  import {
    REGEXP_ONLY_DIGITS,
    type RenderProps,
    type SlotProps,
  } from '@lib/core'
  import { onMount as coreOnMount } from '@lib/core/internal/input'
  import type { HTMLInputElementWithMetadata } from '@lib/core/internal/types'

  interface $$Props extends HTMLInputAttributes {
    value?: string
    oncomplete?: (...args: any[]) => unknown

    // Overriding HTML input props
    autocomplete?: string
    pattern?: string
    disabled?: boolean
    maxlength: number
    inputmode?: 'numeric' | 'text'

    containerClass: string | undefined
  }

  interface $$Slots {
    default: {
      slots: SlotProps[]
      'is-focused': RenderProps['isFocused']
      'is-hovering': RenderProps['isHovering']
    }
  }

  let container: HTMLDivElement
  let input: HTMLInputElement

  /** Attributes */
  export let maxlength: number
  export let pattern = REGEXP_ONLY_DIGITS
  export let inputmode: 'numeric' | 'text' = 'numeric'
  export let autocomplete = 'one-time-code'
  export let disabled = false

  /** Workarounds */
  export let value: string = ''
  let regexp = pattern
    ? typeof pattern === 'string'
      ? new RegExp(pattern)
      : pattern
    : undefined

  /** Props */
  export let containerClass: string | undefined

  /** Mirror State */
  let mirrorFocused = false
  let mirrorHovering = false
  let mirrorSel: [number, number] = [-1, -1]

  let mounted: ReturnType<typeof coreOnMount>
  onMount(() => {
    mounted = coreOnMount({
      container,
      input: input as HTMLInputElementWithMetadata,
      metadata: {
        maxLength: maxlength,
        onChange: t => {
          value = t
        },
        onComplete: t => dispatch('complete', t),
        regexp,
        updateMirror: (k, v) => {
          if (k === 'data-sel' && v !== undefined) {
            const [s, e] = v.split(',').map(Number)
            mirrorSel = [s, e]
          }
          if (k === 'data-is-focused') {
            mirrorFocused = Boolean(v)
          }
          if (k === 'data-is-hovering') {
            mirrorHovering = Boolean(v)
          }
        },
      },
    })
  })
  onDestroy(() => {
    mounted !== undefined && mounted.unmount()
  })

  const dispatch = createEventDispatcher<{
    // Native events
    input: HTMLElementEventMap['input']

    // Custom events
    complete: string
  }>()

  $: slots = Array.from({ length: maxlength }).map((_, slotIdx) => {
    const isActive =
      mirrorFocused &&
      mirrorSel[0] !== null &&
      mirrorSel[1] !== null &&
      ((mirrorSel[0] === mirrorSel[1] && slotIdx === mirrorSel[0]) ||
        (slotIdx >= mirrorSel[0] && slotIdx < mirrorSel[1]))

    const char = value[slotIdx] !== undefined ? value[slotIdx] : null

    return {
      char,
      isActive,
      hasFakeCaret: isActive && char === null,
    }
  })
</script>

<div
  data-input-otp-container
  bind:this={container}
  style="position: relative; user-select: none; -webkit-user-select: none"
  class={containerClass}
>
  <slot
    {slots}
    is-focused={mirrorFocused}
    is-hovering={!disabled && mirrorHovering}
  />

  <input
    data-input-otp
    style="position: absolute; inset: 0; width: 100%; height: 100%; display: flex; text-align: start; opacity: 1; color: transparent; pointer-events: all; background: transparent; caret-color: transparent; border: 0 solid transparent; outline: 0 solid transparent; line-height: 1; letter-spacing: -.5em; font-size: var(--root-height);"
    {...$$restProps}
    bind:value
    bind:this={input}
    pattern={regexp?.source}
    {disabled}
    {autocomplete}
    {inputmode}
    {maxlength}
  />
</div>
