// lib/vue/input.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue'
import { computed, onMounted, onUnmounted, ref } from 'vue'

import { REGEXP_ONLY_DIGITS } from '../core'
import { onMount } from '../core/internal/input'
import type { HTMLInputElementWithMetadata } from '../core/internal/types'

import type { VueOTPInputProps } from './types'

defineOptions({
  name: 'OTPInput',
  inheritAttrs: false,
})

const {
  // Props
  maxlength,
  pattern = REGEXP_ONLY_DIGITS,
  inputmode = 'numeric',

  containerClass,

  // HTML defaults
  autocomplete = 'one-time-code',

  ...props
} = withDefaults(defineProps<VueOTPInputProps>(), {
  pattern: REGEXP_ONLY_DIGITS,
  inputmode: 'numeric',
})

const emit = defineEmits<{
  (event: 'complete', value: string): void
}>()

const value = defineModel({ default: '' })

/** Workarounds */
const onChange = (newValue: string) => {
  value.value = newValue
}
const regexp = computed(() =>
  pattern
    ? typeof pattern === 'string'
      ? new RegExp(pattern)
      : pattern
    : undefined,
)

/** Refs */
const containerRef = ref<HTMLDivElement | null>(null)
const inputRef = ref<HTMLInputElementWithMetadata | null>(null)
defineExpose({ ref: inputRef })

/** Mirror State for children-rendering-only purpose */
const mirrorHovering = ref(false)
const mirrorFocused = ref(false)
const mirrorSel = ref<[number, number]>([-1, -1])

let mounted: ReturnType<typeof onMount>
onMounted(() => {
  const container = containerRef.value
  const input = inputRef.value
  if (!container || !input) {
    return
  }

  mounted = onMount({
    container,
    input: input,
    metadata: {
      maxLength: maxlength,
      onChange,
      onComplete: t => emit('complete', t),
      regexp: regexp.value,
      updateMirror: (k, v) => {
        if (k === 'data-sel' && v !== undefined) {
          const [s, e] = v.split(',').map(Number)
          mirrorSel.value = [s, e]
        }
        if (k === 'data-is-focused') {
          mirrorFocused.value = Boolean(v)
        }
        if (k === 'data-is-hovering') {
          mirrorHovering.value = Boolean(v)
        }
      },
    },
  })
})
onUnmounted(() => {
  mounted !== undefined && mounted.unmount()
})

const slots = computed(() => {
  return Array.from({ length: maxlength }).map((_, slotIdx) => {
    const isActive =
      mirrorFocused.value &&
      mirrorSel.value[0] !== null &&
      mirrorSel.value[1] !== null &&
      ((mirrorSel.value[0] === mirrorSel.value[1] &&
        slotIdx === mirrorSel.value[0]) ||
        (slotIdx >= mirrorSel.value[0] && slotIdx < mirrorSel.value[1]))

    const char =
      value.value[slotIdx] !== undefined ? value.value[slotIdx] : null

    return {
      char,
      isActive,
      hasFakeCaret: isActive && char === null,
    }
  })
})

const inputStyle = {
  position: 'absolute',
  inset: 0,
  width: '100%',
  height: '100%',
  display: 'flex',
  textAlign: 'start',
  opacity: '1', // Mandatory for iOS hold-paste
  color: 'transparent',
  pointerEvents: 'all',
  background: 'transparent',
  caretColor: 'transparent',
  border: '0 solid transparent',
  outline: '0 solid transparent',
  lineHeight: '1',
  letterSpacing: '-.5em',
  fontSize: 'var(--root-height)',
} satisfies CSSProperties
</script>

<template>
  <div
    data-input-otp-container
    ref="containerRef"
    :style="{
      position: 'relative',
      userSelect: 'none',
      cursor: disabled ? 'default' : 'text',
    }"
    :class="containerClass"
  >
    <slot
      :slots="slots"
      :is-focused="mirrorFocused"
      :is-hovering="!disabled && mirrorHovering"
    />

    <input
      v-bind="{ ...$attrs, ...props }"
      :autocomplete="autocomplete"
      data-input-otp
      ref="inputRef"
      :style="inputStyle"
      :pattern="pattern"
      :inputmode="inputmode"
      :maxlength="maxlength"
      :value="value"
    />
  </div>
</template>

// lib/react/input.tsx
import * as React from 'react'

import { onMount } from '../core/internal/input'
import { REGEXP_ONLY_DIGITS } from '../core/regexp'
import type {
  HTMLInputElementWithMetadata,
  UserDefinedMetadata,
} from '../core/internal/types'

import type { ReactOTPInputProps } from './types'

export const OTPInput = React.forwardRef<HTMLInputElement, ReactOTPInputProps>(
  (
    {
      // Props
      value,
      onChange,
      maxLength,
      pattern = REGEXP_ONLY_DIGITS,
      inputMode = 'numeric',
      onComplete,
      render,
      containerClassName,

      // HTML defaults
      autoComplete = 'one-time-code',
      ...props
    },
    ref,
  ) => {
    /** Workarounds */
    const regexp = React.useMemo(
      () =>
        pattern
          ? typeof pattern === 'string'
            ? new RegExp(pattern)
            : pattern
          : undefined,
      [pattern],
    )

    /** Refs */
    const containerRef = React.useRef<HTMLDivElement>(null)
    const inputRef = React.useRef<HTMLInputElementWithMetadata>(null)
    React.useImperativeHandle(ref, () => inputRef.current!, [])

    /** Mirror State for children-rendering-only purpose */
    const [mirrorFocused, setMirrorFocused] = React.useState(false)
    const [mirrorHovering, setMirrorHovering] = React.useState(false)
    const [mirrorSel, setMirrorSel] = React.useState<[number, number]>([-1, -1])

    /** Mount and Unmount */
    React.useEffect(() => {
      const container = containerRef.current
      const input = inputRef.current

      if (!container || !input) {
        return
      }

      const m: UserDefinedMetadata = {
        maxLength,
        onChange: t => {
          onChange?.(t)
        },
        onComplete,
        regexp,
        updateMirror: (k, v) => {
          if (k === 'data-sel' && v !== undefined) {
            const [s, e] = v.split(',').map(Number)
            setMirrorSel([s, e])
          }
          if (k === 'data-is-focused') {
            setMirrorFocused(Boolean(v))
          }
          if (k === 'data-is-hovering') {
            setMirrorHovering(Boolean(v))
          }
        },
      }

      // mount or update metadata
      if (input.__metadata__ === undefined) {
        onMount({
          container,
          input,
          metadata: m,
        })
      } else {
        input.__metadata__ = Object.assign(input.__metadata__, m)
      }
    }, [maxLength, onChange, regexp])
    React.useEffect(() => {
      return () => {
        inputRef.current?.__metadata__?.unmount?.()
      }
    }, [])

    /** JSX */
    const renderedInput = React.useMemo(
      () => (
        <input
          autoComplete={autoComplete}
          onChange={() => {}}
          {...props}
          data-input-otp
          ref={inputRef}
          inputMode={inputMode}
          pattern={regexp?.source}
          style={inputStyle}
          maxLength={maxLength}
          value={value}
        />
      ),
      [autoComplete, props, inputMode, regexp, maxLength, value],
    )

    const renderedChildren = React.useMemo<ReturnType<typeof render>>(() => {
      return render({
        slots: Array.from({ length: maxLength }).map((_, slotIdx) => {
          const isActive =
            mirrorFocused &&
            mirrorSel[0] !== null &&
            mirrorSel[1] !== null &&
            ((mirrorSel[0] === mirrorSel[1] && slotIdx === mirrorSel[0]) ||
              (slotIdx >= mirrorSel[0] && slotIdx < mirrorSel[1]))

          const _value = value || inputRef.current?.value
          const char =
            typeof _value === 'string'
              ? _value[slotIdx] !== undefined
                ? _value[slotIdx]
                : null
              : null

          return {
            char,
            isActive,
            hasFakeCaret: isActive && char === null,
          }
        }),
        isFocused: mirrorFocused,
        isHovering: !props.disabled && mirrorHovering,
      })
    }, [
      render,
      maxLength,
      mirrorFocused,
      props.disabled,
      mirrorHovering,
      value,
      mirrorSel,
    ])

    return (
      <div
        data-input-otp-container
        ref={containerRef}
        style={rootStyle({ disabled: props.disabled })}
        className={containerClassName}
      >
        {renderedChildren}
        {renderedInput}
      </div>
    )
  },
)
OTPInput.displayName = 'OTPInput'

const rootStyle = (params: { disabled?: boolean }) =>
  ({
    position: 'relative',
    cursor: params.disabled ? 'default' : 'text',
    userSelect: 'none',
    WebkitUserSelect: 'none',
  } satisfies React.CSSProperties)

const inputStyle = {
  position: 'absolute',
  inset: 0,
  width: '100%',
  height: '100%',
  display: 'flex',
  textAlign: 'start',
  opacity: '1', // Mandatory for iOS hold-paste
  color: 'transparent',
  pointerEvents: 'all',
  background: 'transparent',
  caretColor: 'transparent',
  border: '0 solid transparent',
  outline: '0 solid transparent',
  lineHeight: '1',
  letterSpacing: '-.5em',
  fontSize: 'var(--root-height)',
  // letterSpacing: '-1em',
  // transform: 'scale(1.5)',
  // paddingRight: '100%',
  // paddingBottom: '100%',
  // debugging purposes
  // inset: undefined,
  // position: undefined,
  // color: 'black',
  // background: 'white',
  // opacity: '.5',
  // caretColor: 'black',
  // padding: '0',
} satisfies React.CSSProperties
